function g = DAE_g(in1,u1,in3,alpha)
%DAE_G
%    G = DAE_G(IN1,U1,IN3,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    21-Nov-2018 17:15:57

lambda2 = in1(4,:);
g = lambda2+u1.*1.0;
